import GithubSlugger from 'github-slugger';
import type { SidebarLink } from '../types';

export interface HeadingData {
  depth: number;
  text: string;
  slug: string;
}

/**
 * Extract headings from markdown content using regex.
 * Uses github-slugger to match the IDs generated by rehype-slug.
 */
export const extractHeadings = (markdown: string): HeadingData[] => {
  const slugger = new GithubSlugger();
  const headings: HeadingData[] = [];

  // Match markdown headings: ## Heading or ### Heading etc.
  const headingRegex = /^(#{1,6})\s+(.+)$/gm;
  let match;

  while ((match = headingRegex.exec(markdown)) !== null) {
    const depth = match[1].length;
    const text = match[2].trim();
    const slug = slugger.slug(text);

    headings.push({ depth, text, slug });
  }

  return headings;
};

/**
 * Convert extracted headings to sidebar links.
 */
export const headingsToSidebarLinks = (
  headings: HeadingData[],
  options: { includeDepths?: number[]; addApplyLink?: boolean } = {}
): SidebarLink[] => {
  const { includeDepths = [2], addApplyLink = true } = options;

  const links: SidebarLink[] = headings
    .filter(h => includeDepths.includes(h.depth))
    .map(h => ({
      text: h.text,
      href: `#${h.slug}`
    }));

  if (addApplyLink) {
    links.push({ text: 'Apply', href: '#apply' });
  }

  return links;
};
