import { Container, Flex, Heading } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const About: NextPage = () => {
  return (
    <Container maxW='2xl'>
      <Head>
        <title>About</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Flex py={16} minH='100vh' direction='column' justify='center' align='center'>
        <main>
          <Heading as='h1' size='2xl' mb={6}>
            About
          </Heading>
        </main>
      </Flex>
    </Container>
  );
};

export default About;
